kind: pipeline
type: docker # Specifies the runner type
name: default

trigger:
  branch:
    - main # Only run this pipeline for commits to the main branch

steps:
  - name: test
    image: golang:1.19 # Or node, python, etc.
    commands:
      - echo "Running unit tests..."
      # - go test -v ./...

  - name: build_and_push
    image: plugins/docker # Use the official Docker plugin for Drone
    depends_on: [ test ] # Only run if the 'test' step succeeds
    settings:
      # Credentials for Nexus (from Drone secrets)
      username:
        from_secret: NEXUS_USER
      password:
        from_secret: NEXUS_PASS
      
      # Build & Push Details
      # Use the service name 'nexus' for inter-container communication
      repo: nexus:8082/docker-private/my-app
      tags:
        - ${DRONE_COMMIT_SHA:0:7} # Tag with the short commit hash
        - latest
      dockerfile: Dockerfile # Assumes a 'Dockerfile' is in your repo
      context: .
      insecure: true # Required for connecting to Nexus via HTTP
      
      # <-- IMPROVEMENT: Use the 'latest' tag as a cache source for faster builds
      cache_from:
        - nexus:8082/docker-private/my-app:latest