kind: pipeline
type: docker # Specifies the runner type
name: default
trigger:
  branch:
    - main # Or `master`, depending on your repository's default branch

steps:
  - name: lint
    image: golangci/golangci-lint:v1.59
    commands:
      - echo "Running linter..."
      # - golangci-lint run

  - name: test
    image: golang:1.22
    commands:
      - echo "Running unit tests..."
      # - go test -v ./...

  - name: build_and_push
    image: plugins/docker # Use the official Docker plugin for Drone
    settings:
      # Credentials for Nexus (from Drone secrets)
      username:
        from_secret: NEXUS_USER
      password:
        from_secret: NEXUS_PASS

      # Build & Push Details
      # IMPROVEMENT: Use the secure, public-facing Nexus host.
      # The NEXUS_REGISTRY_HOST variable must be defined as a secret in Drone.
      repo: ${NEXUS_REGISTRY_HOST}/my-app
      tags:
        - ${DRONE_COMMIT_SHA:0:7} # Tag with the short commit hash
        - latest
      dockerfile: Dockerfile
      context: .
      # IMPROVEMENT: Enable Docker layer caching to speed up builds.
      # This reuses layers from the 'latest' tag of the image.
      cache_from: [ "${NEXUS_REGISTRY_HOST}/my-app:latest" ]
      insecure: false # Ensure we are connecting securely