kind: pipeline
type: docker # Specifies the runner type
name: default
trigger:
  event:
    - push
    - tag
    - pull_request
 
steps:
  - name: lint
    image: golangci/golangci-lint:v1.59
    commands:
      - echo "Running linter..."
      # - golangci-lint run

  - name: test
    image: golang:1.22
    commands:
      - echo "Running unit tests..."
      # - go test -v ./...
    volumes:
      - name: go-cache
        path: /go
  - name: build_for_pr
    image: plugins/docker
    settings:
      # This step only builds the image to validate the Dockerfile, but does not push.
      repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
      tags: [ "pr-${DRONE_PULL_REQUEST}" ]
      dry_run: true # This is the key setting to prevent pushing
      registry: ${NEXUS_REGISTRY_HOST}
      username:
        from_secret: NEXUS_USER
      password:
        from_secret: NEXUS_PASS
    trigger:
      event:
        - pull_request

  - name: build
    image: plugins/docker # Use the official Docker plugin for Drone
    settings:
      username:
        from_secret: NEXUS_USER
      password:
        from_secret: NEXUS_PASS
      repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
      # Build and push a temporary image with the commit SHA for scanning
      tags: [ "${DRONE_COMMIT_SHA:0:7}" ]
      dockerfile: Dockerfile
      context: .
      registry: ${NEXUS_REGISTRY_HOST} # The NEXUS_REGISTRY_HOST variable must be defined as a secret in Drone.
      cache_from: [ "${NEXUS_REGISTRY_HOST}/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:latest" ]
      insecure: false # Ensure we are connecting securely
    trigger:
      event: [ push, tag ]
      branch: [ main ]
    depends_on: [ test ]

  - name: scan
    image: aquasec/trivy:0.52
    settings:
      # Scan the temporary image we just pushed
      input: "${NEXUS_REGISTRY_HOST}/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:${DRONE_COMMIT_SHA:0:7}"
      severity: "HIGH,CRITICAL" # Fail the build if HIGH or CRITICAL vulnerabilities are found
      exit_code: 1
      ignore_unfixed: true
      # Trivy needs the Nexus credentials to pull the image for scanning
      registry_username:
        from_secret: NEXUS_USER
      registry_password:
        from_secret: NEXUS_PASS
    trigger:
      event: [ push, tag ]
      branch: [ main ]
    depends_on: [ build ]

  - name: promote
    image: plugins/docker
    settings:
      username:
        from_secret: NEXUS_USER
      password:
        from_secret: NEXUS_PASS
      repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
      # Re-tag the scanned image with its final version/latest tag
      tags: >
        {{#if build.tag}}
        [ "${DRONE_COMMIT_SHA:0:7}", "{{build.tag}}" ]
        {{else}}
        [ "${DRONE_COMMIT_SHA:0:7}", "latest" ]
        {{/if}}
      registry: ${NEXUS_REGISTRY_HOST}
      # This step re-tags the scanned image. Because the image layers already exist
      # in the registry, this is a fast manifest-only operation, not a full rebuild.
    trigger:
      event: [ push, tag ]
      branch: [ main ]
    depends_on: [ scan ]

volumes:
  - name: go-cache
    path: /go